package com.mac.runtu.databasehelper;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ADDRESS_DATA_INFO".
 */
public class AddressDataInfo {

    private Long id;
    /** Not-null value. */
    public String district_code;
    public String district_name;
    public String latitude;
    public String longitude;
    public String parent_code;

    public AddressDataInfo() {
    }

    public AddressDataInfo(Long id) {
        this.id = id;
    }

    public AddressDataInfo(Long id, String district_code, String district_name, String latitude, String longitude, String parent_code) {
        this.id = id;
        this.district_code = district_code;
        this.district_name = district_name;
        this.latitude = latitude;
        this.longitude = longitude;
        this.parent_code = parent_code;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getDistrict_code() {
        return district_code;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDistrict_code(String district_code) {
        this.district_code = district_code;
    }

    public String getDistrict_name() {
        return district_name;
    }

    public void setDistrict_name(String district_name) {
        this.district_name = district_name;
    }

    public String getLatitude() {
        return latitude;
    }

    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }

    public String getLongitude() {
        return longitude;
    }

    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }

    public String getParent_code() {
        return parent_code;
    }

    public void setParent_code(String parent_code) {
        this.parent_code = parent_code;
    }

    @Override
    public String toString() {
        return "AddressDataInfo{" +
                "id=" + id +
                ", district_code='" + district_code + '\'' +
                ", district_name='" + district_name + '\'' +
                ", latitude='" + latitude + '\'' +
                ", longitude='" + longitude + '\'' +
                ", parent_code='" + parent_code + '\'' +
                '}';
    }
}
