package com.mac.runtu.databasehelper;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig addressDataInfoDaoConfig;

    private final AddressDataInfoDao addressDataInfoDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        addressDataInfoDaoConfig = daoConfigMap.get(AddressDataInfoDao.class).clone();
        addressDataInfoDaoConfig.initIdentityScope(type);

        addressDataInfoDao = new AddressDataInfoDao(addressDataInfoDaoConfig, this);

        registerDao(AddressDataInfo.class, addressDataInfoDao);
    }
    
    public void clear() {
        addressDataInfoDaoConfig.getIdentityScope().clear();
    }

    public AddressDataInfoDao getAddressDataInfoDao() {
        return addressDataInfoDao;
    }

}
